"""
This type stub file was generated by pyright.
"""

from datetime import datetime, timedelta
from typing import Any, Awaitable, Iterable, Mapping, Protocol, TYPE_CHECKING, Type, TypeVar, Union
from redis._parsers import Encoder

if TYPE_CHECKING:
    ...
Number = Union[int, float]
EncodedT = Union[bytes, bytearray, memoryview]
DecodedT = Union[str, int, float]
EncodableT = Union[EncodedT, DecodedT]
AbsExpiryT = Union[int, datetime]
ExpiryT = Union[int, timedelta]
ZScoreBoundT = Union[float, str]
BitfieldOffsetT = Union[int, str]
_StringLikeT = Union[bytes, str, memoryview]
KeyT = _StringLikeT
PatternT = _StringLikeT
FieldT = EncodableT
KeysT = Union[KeyT, Iterable[KeyT]]
ResponseT = Union[Awaitable[Any], Any]
ChannelT = _StringLikeT
GroupT = _StringLikeT
ConsumerT = _StringLikeT
StreamIdT = Union[int, _StringLikeT]
ScriptTextT = _StringLikeT
TimeoutSecT = Union[int, float, _StringLikeT]
AnyKeyT = TypeVar("AnyKeyT", bytes, str, memoryview)
AnyFieldT = TypeVar("AnyFieldT", bytes, str, memoryview)
AnyChannelT = TypeVar("AnyChannelT", bytes, str, memoryview)
ExceptionMappingT = Mapping[str, Union[Type[Exception], Mapping[str, Type[Exception]]]]
class CommandsProtocol(Protocol):
    def execute_command(self, *args, **options) -> ResponseT:
        ...
    


class ClusterCommandsProtocol(CommandsProtocol):
    encoder: Encoder
    ...


