"""
This type stub file was generated by pyright.
"""

from collections.abc import Callable
from contextlib import contextmanager
from typing import Any, Dict, List, Mapping, Optional, TypeVar, Union
from redis.typing import AbsExpiryT, EncodableT, ExpiryT

hiredis_version = ...
HIREDIS_AVAILABLE = ...
if not HIREDIS_AVAILABLE:
    ...
SSL_AVAILABLE = ...
CRYPTOGRAPHY_AVAILABLE = ...
def from_url(url, **kwargs): # -> Redis:
    """
    Returns an active Redis client generated from the given database URL.

    Will attempt to extract the database id from the path url fragment, if
    none is provided.
    """
    ...

@contextmanager
def pipeline(redis_obj): # -> Generator[Any, Any, None]:
    ...

def str_if_bytes(value: Union[str, bytes]) -> str:
    ...

def safe_str(value): # -> str:
    ...

def dict_merge(*dicts: Mapping[str, Any]) -> Dict[str, Any]:
    """
    Merge all provided dicts into 1 dict.
    *dicts : `dict`
        dictionaries to merge
    """
    ...

def list_keys_to_dict(key_list, callback): # -> dict[Any, Any | None]:
    ...

def merge_result(command, res): # -> list[Any]:
    """
    Merge all items in `res` into a list.

    This command is used when sending a command to multiple nodes
    and the result from each node should be merged into a single list.

    res : 'dict'
    """
    ...

def warn_deprecated(name, reason=..., version=..., stacklevel=...): # -> None:
    ...

def deprecated_function(reason=..., version=..., name=...): # -> Callable[..., _Wrapped[Callable[..., Any], Any, Callable[..., Any], Any]]:
    """
    Decorator to mark a function as deprecated.
    """
    ...

def warn_deprecated_arg_usage(arg_name: Union[list, str], function_name: str, reason: str = ..., version: str = ..., stacklevel: int = ...): # -> None:
    ...

C = TypeVar("C", bound=Callable)
def deprecated_args(args_to_warn: list = ..., allowed_args: list = ..., reason: str = ..., version: str = ...) -> Callable[[C], C]:
    """
    Decorator to mark specified args of a function as deprecated.
    If '*' is in args_to_warn, all arguments will be marked as deprecated.
    """
    ...

def get_lib_version(): # -> str:
    ...

def format_error_message(host_error: str, exception: BaseException) -> str:
    ...

def compare_versions(version1: str, version2: str) -> int:
    """
    Compare two versions.

    :return: -1 if version1 > version2
             0 if both versions are equal
             1 if version1 < version2
    """
    ...

def ensure_string(key): # -> str:
    ...

def extract_expire_flags(ex: Optional[ExpiryT] = ..., px: Optional[ExpiryT] = ..., exat: Optional[AbsExpiryT] = ..., pxat: Optional[AbsExpiryT] = ...) -> List[EncodableT]:
    ...

def truncate_text(txt, max_length=...): # -> str:
    ...

