version: "3.9"

services:
  redis:
    image: redis/redis-stack-server:latest
    container_name: redis
    ports:
      - "6379:6379"

  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: masterkey
      POSTGRES_DB: postgres
    ports:
      - "5555:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "1883:1883"   # MQTT
      - "5672:5672"   # AMQP
      - "15672:15672" # Management UI
    command: >
      bash -c "rabbitmq-plugins enable --offline rabbitmq_mqtt &&
               rabbitmq-server"

volumes:
  pgdata: