"""
This type stub file was generated by pyright.
"""

from typing import List, Tuple
from redis.typing import KeyT, KeysT

def list_or_args(keys: KeysT, args: Tuple[KeyT, ...]) -> List[KeyT]:
    ...

def nativestr(x): # -> str | None:
    """Return the decoded binary string, or a string, depending on type."""
    ...

def delist(x): # -> list[str | Any | None]:
    """Given a list of binaries, return the stringified version."""
    ...

def parse_to_list(response): # -> list[Any]:
    """Optimistically parse the response to a list."""
    ...

def parse_list_to_dict(response): # -> dict[Any, Any]:
    ...

def random_string(length=...): # -> str:
    """
    Returns a random N character long string.
    """
    ...

def decode_dict_keys(obj):
    """Decode the keys of the given dictionary with utf-8."""
    ...

def get_protocol_version(client): # -> None:
    ...

