"""
This type stub file was generated by pyright.
"""

from typing import Any, AsyncIterator, Awaitable, Callable, Dict, Iterable, List, Mapping, MutableMapping, Optional, Protocol, TYPE_CHECKING, Tuple, Type, TypeVar, TypedDict, Union
import typing
from redis._parsers.encoders import Encoder
from redis.asyncio.connection import Connection, ConnectionPool
from redis.asyncio.lock import Lock
from redis.asyncio.retry import Retry
from redis.client import AbstractRedis
from redis.commands import AsyncCoreCommands, AsyncRedisModuleCommands, AsyncSentinelCommands
from redis.credentials import CredentialProvider
from redis.event import EventDispatcher
from redis.typing import ChannelT, EncodableT, KeyT
from redis.utils import SSL_AVAILABLE, deprecated_args, deprecated_function
from ssl import TLSVersion, VerifyMode

if TYPE_CHECKING and SSL_AVAILABLE:
    ...
else:
    TLSVersion = ...
    VerifyMode = ...
PubSubHandler = Callable[[Dict[str, str]], Awaitable[None]]
_KeyT = TypeVar("_KeyT", bound=KeyT)
_ArgT = TypeVar("_ArgT", KeyT, EncodableT)
_RedisT = TypeVar("_RedisT", bound="Redis")
_NormalizeKeysT = TypeVar("_NormalizeKeysT", bound=Mapping[ChannelT, object])
if TYPE_CHECKING:
    ...
class ResponseCallbackProtocol(Protocol):
    def __call__(self, response: Any, **kwargs): # -> None:
        ...
    


class AsyncResponseCallbackProtocol(Protocol):
    async def __call__(self, response: Any, **kwargs): # -> None:
        ...
    


ResponseCallbackT = Union[ResponseCallbackProtocol, AsyncResponseCallbackProtocol]
class Redis(AbstractRedis, AsyncRedisModuleCommands, AsyncCoreCommands, AsyncSentinelCommands):
    """
    Implementation of the Redis protocol.

    This abstract class provides a Python interface to all Redis commands
    and an implementation of the Redis protocol.

    Pipelines derive from this, implementing how
    the commands are sent and received to the Redis server. Based on
    configuration, an instance will either use a ConnectionPool, or
    Connection object to talk to redis.
    """
    response_callbacks: MutableMapping[Union[str, bytes], ResponseCallbackT]
    @classmethod
    def from_url(cls, url: str, single_connection_client: bool = ..., auto_close_connection_pool: Optional[bool] = ..., **kwargs): # -> Self:
        """
        Return a Redis client object configured from the given URL

        For example::

            redis://[[username]:[password]]@localhost:6379/0
            rediss://[[username]:[password]]@localhost:6379/0
            unix://[username@]/path/to/socket.sock?db=0[&password=password]

        Three URL schemes are supported:

        - `redis://` creates a TCP socket connection. See more at:
          <https://www.iana.org/assignments/uri-schemes/prov/redis>
        - `rediss://` creates a SSL wrapped TCP socket connection. See more at:
          <https://www.iana.org/assignments/uri-schemes/prov/rediss>
        - ``unix://``: creates a Unix Domain Socket connection.

        The username, password, hostname, path and all querystring values
        are passed through urllib.parse.unquote in order to replace any
        percent-encoded values with their corresponding characters.

        There are several ways to specify a database number. The first value
        found will be used:

        1. A ``db`` querystring option, e.g. redis://localhost?db=0

        2. If using the redis:// or rediss:// schemes, the path argument
               of the url, e.g. redis://localhost/0

        3. A ``db`` keyword argument to this function.

        If none of these options are specified, the default db=0 is used.

        All querystring options are cast to their appropriate Python types.
        Boolean arguments can be specified with string values "True"/"False"
        or "Yes"/"No". Values that cannot be properly cast cause a
        ``ValueError`` to be raised. Once parsed, the querystring arguments
        and keyword arguments are passed to the ``ConnectionPool``'s
        class initializer. In the case of conflicting arguments, querystring
        arguments always win.

        """
        ...
    
    @classmethod
    def from_pool(cls: Type[Redis], connection_pool: ConnectionPool) -> Redis:
        """
        Return a Redis client from the given connection pool.
        The Redis client will take ownership of the connection pool and
        close it when the Redis client is closed.
        """
        ...
    
    @deprecated_args(args_to_warn=["retry_on_timeout"], reason="TimeoutError is included by default.", version="6.0.0")
    def __init__(self, *, host: str = ..., port: int = ..., db: Union[str, int] = ..., password: Optional[str] = ..., socket_timeout: Optional[float] = ..., socket_connect_timeout: Optional[float] = ..., socket_keepalive: Optional[bool] = ..., socket_keepalive_options: Optional[Mapping[int, Union[int, bytes]]] = ..., connection_pool: Optional[ConnectionPool] = ..., unix_socket_path: Optional[str] = ..., encoding: str = ..., encoding_errors: str = ..., decode_responses: bool = ..., retry_on_timeout: bool = ..., retry: Retry = ..., retry_on_error: Optional[list] = ..., ssl: bool = ..., ssl_keyfile: Optional[str] = ..., ssl_certfile: Optional[str] = ..., ssl_cert_reqs: Union[str, VerifyMode] = ..., ssl_ca_certs: Optional[str] = ..., ssl_ca_data: Optional[str] = ..., ssl_check_hostname: bool = ..., ssl_min_version: Optional[TLSVersion] = ..., ssl_ciphers: Optional[str] = ..., max_connections: Optional[int] = ..., single_connection_client: bool = ..., health_check_interval: int = ..., client_name: Optional[str] = ..., lib_name: Optional[str] = ..., lib_version: Optional[str] = ..., username: Optional[str] = ..., auto_close_connection_pool: Optional[bool] = ..., redis_connect_func=..., credential_provider: Optional[CredentialProvider] = ..., protocol: Optional[int] = ..., event_dispatcher: Optional[EventDispatcher] = ...) -> None:
        """
        Initialize a new Redis client.

        To specify a retry policy for specific errors, you have two options:

        1. Set the `retry_on_error` to a list of the error/s to retry on, and
        you can also set `retry` to a valid `Retry` object(in case the default
        one is not appropriate) - with this approach the retries will be triggered
        on the default errors specified in the Retry object enriched with the
        errors specified in `retry_on_error`.

        2. Define a `Retry` object with configured 'supported_errors' and set
        it to the `retry` parameter - with this approach you completely redefine
        the errors on which retries will happen.

        `retry_on_timeout` is deprecated - please include the TimeoutError
        either in the Retry object or in the `retry_on_error` list.

        When 'connection_pool' is provided - the retry configuration of the
        provided pool will be used.
        """
        ...
    
    def __repr__(self): # -> str:
        ...
    
    def __await__(self): # -> Generator[Any, None, Self]:
        ...
    
    async def initialize(self: _RedisT) -> _RedisT:
        ...
    
    def set_response_callback(self, command: str, callback: ResponseCallbackT): # -> None:
        """Set a custom Response Callback"""
        ...
    
    def get_encoder(self):
        """Get the connection pool's encoder"""
        ...
    
    def get_connection_kwargs(self): # -> dict[str, Any]:
        """Get the connection's key-word arguments"""
        ...
    
    def get_retry(self) -> Optional[Retry]:
        ...
    
    def set_retry(self, retry: Retry) -> None:
        ...
    
    def load_external_module(self, funcname, func): # -> None:
        """
        This function can be used to add externally defined redis modules,
        and their namespaces to the redis client.

        funcname - A string containing the name of the function to create
        func - The function, being added to this class.

        ex: Assume that one has a custom redis module named foomod that
        creates command named 'foo.dothing' and 'foo.anotherthing' in redis.
        To load function functions into this namespace:

        from redis import Redis
        from foomodule import F
        r = Redis()
        r.load_external_module("foo", F)
        r.foo().dothing('your', 'arguments')

        For a concrete example see the reimport of the redisjson module in
        tests/test_connection.py::test_loading_external_modules
        """
        ...
    
    def pipeline(self, transaction: bool = ..., shard_hint: Optional[str] = ...) -> Pipeline:
        """
        Return a new pipeline object that can queue multiple commands for
        later execution. ``transaction`` indicates whether all commands
        should be executed atomically. Apart from making a group of operations
        atomic, pipelines are useful for reducing the back-and-forth overhead
        between the client and server.
        """
        ...
    
    async def transaction(self, func: Callable[[Pipeline], Union[Any, Awaitable[Any]]], *watches: KeyT, shard_hint: Optional[str] = ..., value_from_callable: bool = ..., watch_delay: Optional[float] = ...): # -> Any | List[Any]:
        """
        Convenience method for executing the callable `func` as a transaction
        while watching all keys specified in `watches`. The 'func' callable
        should expect a single argument which is a Pipeline object.
        """
        ...
    
    def lock(self, name: KeyT, timeout: Optional[float] = ..., sleep: float = ..., blocking: bool = ..., blocking_timeout: Optional[float] = ..., lock_class: Optional[Type[Lock]] = ..., thread_local: bool = ..., raise_on_release_error: bool = ...) -> Lock:
        """
        Return a new Lock object using key ``name`` that mimics
        the behavior of threading.Lock.

        If specified, ``timeout`` indicates a maximum life for the lock.
        By default, it will remain locked until release() is called.

        ``sleep`` indicates the amount of time to sleep per loop iteration
        when the lock is in blocking mode and another client is currently
        holding the lock.

        ``blocking`` indicates whether calling ``acquire`` should block until
        the lock has been acquired or to fail immediately, causing ``acquire``
        to return False and the lock not being acquired. Defaults to True.
        Note this value can be overridden by passing a ``blocking``
        argument to ``acquire``.

        ``blocking_timeout`` indicates the maximum amount of time in seconds to
        spend trying to acquire the lock. A value of ``None`` indicates
        continue trying forever. ``blocking_timeout`` can be specified as a
        float or integer, both representing the number of seconds to wait.

        ``lock_class`` forces the specified lock implementation. Note that as
        of redis-py 3.0, the only lock class we implement is ``Lock`` (which is
        a Lua-based lock). So, it's unlikely you'll need this parameter, unless
        you have created your own custom lock class.

        ``thread_local`` indicates whether the lock token is placed in
        thread-local storage. By default, the token is placed in thread local
        storage so that a thread only sees its token, not a token set by
        another thread. Consider the following timeline:

            time: 0, thread-1 acquires `my-lock`, with a timeout of 5 seconds.
                     thread-1 sets the token to "abc"
            time: 1, thread-2 blocks trying to acquire `my-lock` using the
                     Lock instance.
            time: 5, thread-1 has not yet completed. redis expires the lock
                     key.
            time: 5, thread-2 acquired `my-lock` now that it's available.
                     thread-2 sets the token to "xyz"
            time: 6, thread-1 finishes its work and calls release(). if the
                     token is *not* stored in thread local storage, then
                     thread-1 would see the token value as "xyz" and would be
                     able to successfully release the thread-2's lock.

        ``raise_on_release_error`` indicates whether to raise an exception when
        the lock is no longer owned when exiting the context manager. By default,
        this is True, meaning an exception will be raised. If False, the warning
        will be logged and the exception will be suppressed.

        In some use cases it's necessary to disable thread local storage. For
        example, if you have code where one thread acquires a lock and passes
        that lock instance to a worker thread to release later. If thread
        local storage isn't disabled in this case, the worker thread won't see
        the token set by the thread that acquired the lock. Our assumption
        is that these cases aren't common and as such default to using
        thread local storage."""
        ...
    
    def pubsub(self, 
        shard_hint: Optional[str] = None,
        ignore_subscribe_messages: bool = False,
        encoder: Encoder | None = None,
        push_handler_func: Optional[Callable[..., None]] = None,
        event_dispatcher: Optional["EventDispatcher"] = None) -> PubSub:
        """
        Return a Publish/Subscribe object. With this object, you can
        subscribe to channels and listen for messages that get published to
        them.
        """
        ...
    
    def monitor(self) -> Monitor:
        ...
    
    def client(self) -> Redis:
        ...
    
    async def __aenter__(self: _RedisT) -> _RedisT:
        ...
    
    async def __aexit__(self, exc_type, exc_value, traceback): # -> None:
        ...
    
    _DEL_MESSAGE = ...
    def __del__(self, _warn: Any = ..., _grl: Any = ...) -> None:
        ...
    
    async def aclose(self, close_connection_pool: Optional[bool] = ...) -> None:
        """
        Closes Redis client connection

        Args:
            close_connection_pool:
                decides whether to close the connection pool used by this Redis client,
                overriding Redis.auto_close_connection_pool.
                By default, let Redis.auto_close_connection_pool decide
                whether to close the connection pool.
        """
        ...
    
    @deprecated_function(version="5.0.1", reason="Use aclose() instead", name="close")
    async def close(self, close_connection_pool: Optional[bool] = ...) -> None:
        """
        Alias for aclose(), for backwards compatibility
        """
        ...
    
    async def execute_command(self, *args, **options): # -> None:
        """Execute a command and return a parsed response"""
        ...
    
    async def parse_response(self, connection: Connection, command_name: Union[str, bytes], **options): # -> None:
        """Parses a response from the Redis server"""
        ...
    


StrictRedis = Redis
class MonitorCommandInfo(TypedDict):
    time: float
    db: int
    client_address: str
    client_port: str
    client_type: str
    command: str
    ...


class Monitor:
    """
    Monitor is useful for handling the MONITOR command to the redis server.
    next_command() method returns one command from monitor
    listen() method yields commands from monitor.
    """
    monitor_re = ...
    command_re = ...
    def __init__(self, connection_pool: ConnectionPool) -> None:
        ...
    
    async def connect(self): # -> None:
        ...
    
    async def __aenter__(self): # -> Self:
        ...
    
    async def __aexit__(self, *args): # -> None:
        ...
    
    async def next_command(self) -> MonitorCommandInfo:
        """Parse the response from a monitor command"""
        ...
    
    async def listen(self) -> AsyncIterator[MonitorCommandInfo]:
        """Listen for commands coming to the server."""
        ...
    


class PubSub:
    """
    PubSub provides publish, subscribe and listen support to Redis channels.

    After subscribing to one or more channels, the listen() method will block
    until a message arrives on one of the subscribed channels. That message
    will be returned and it's safe to start listening again.
    """
    PUBLISH_MESSAGE_TYPES = ...
    UNSUBSCRIBE_MESSAGE_TYPES = ...
    HEALTH_CHECK_MESSAGE = ...
    def __init__(self, connection_pool: ConnectionPool, shard_hint: Optional[str] = ..., ignore_subscribe_messages: bool = ..., encoder=..., push_handler_func: Optional[Callable] = ..., event_dispatcher: Optional[EventDispatcher] = ...) -> None:
        ...
    
    async def __aenter__(self) -> typing.Self: # -> Self:
        ...
    
    async def __aexit__(self, exc_type, exc_value, traceback): # -> None:
        ...
    
    def __del__(self): # -> None:
        ...
    
    async def aclose(self): # -> None:
        ...
    
    @deprecated_function(version="5.0.1", reason="Use aclose() instead", name="close")
    async def close(self) -> None:
        """Alias for aclose(), for backwards compatibility"""
        ...
    
    @deprecated_function(version="5.0.1", reason="Use aclose() instead", name="reset")
    async def reset(self) -> None:
        """Alias for aclose(), for backwards compatibility"""
        ...
    
    async def on_connect(self, connection: Connection): # -> None:
        """Re-subscribe to any channels and patterns previously subscribed to"""
        ...
    
    @property
    def subscribed(self): # -> bool:
        """Indicates if there are subscriptions to any channels or patterns"""
        ...
    
    async def execute_command(self, *args: EncodableT): # -> None:
        """Execute a publish/subscribe command"""
        ...
    
    async def connect(self): # -> None:
        """
        Ensure that the PubSub is connected
        """
        ...
    
    async def parse_response(self, block: bool = ..., timeout: float = ...): # -> None:
        """Parse the response from a publish/subscribe command"""
        ...
    
    async def check_health(self): # -> None:
        ...
    
    async def psubscribe(self, *args: ChannelT, **kwargs: PubSubHandler): # -> None:
        """
        Subscribe to channel patterns. Patterns supplied as keyword arguments
        expect a pattern name as the key and a callable as the value. A
        pattern's callable will be invoked automatically when a message is
        received on that pattern rather than producing a message via
        ``listen()``.
        """
        ...
    
    def punsubscribe(self, *args: ChannelT) -> Awaitable:
        """
        Unsubscribe from the supplied patterns. If empty, unsubscribe from
        all patterns.
        """
        ...
    
    async def subscribe(self, *args: ChannelT, **kwargs: Callable) -> None:
        """
        Subscribe to channels. Channels supplied as keyword arguments expect
        a channel name as the key and a callable as the value. A channel's
        callable will be invoked automatically when a message is received on
        that channel rather than producing a message via ``listen()`` or
        ``get_message()``.
        """
        ...
    
    def unsubscribe(self, *args) -> Awaitable:
        """
        Unsubscribe from the supplied channels. If empty, unsubscribe from
        all channels
        """
        ...
    
    async def listen(self) -> AsyncIterator:
        """Listen for messages on channels this client has been subscribed to"""
        ...
    
    async def get_message(self, ignore_subscribe_messages: bool = ..., timeout: Optional[float] = ...): # -> dict[str, Any] | None:
        """
        Get the next message if one is available, otherwise None.

        If timeout is specified, the system will wait for `timeout` seconds
        before returning. Timeout should be specified as a floating point
        number or None to wait indefinitely.
        """
        ...
    
    def ping(self, message=...) -> Awaitable:
        """
        Ping the Redis server
        """
        ...
    
    async def handle_message(self, response, ignore_subscribe_messages=...): # -> dict[str, Any] | None:
        """
        Parses a pub/sub message. If the channel or pattern was subscribed to
        with a message handler, the handler is invoked instead of a parsed
        message being returned.
        """
        ...
    
    async def run(self, *, exception_handler: Optional[PSWorkerThreadExcHandlerT] = ..., poll_timeout: float = ...) -> None:
        """Process pub/sub messages using registered callbacks.

        This is the equivalent of :py:meth:`redis.PubSub.run_in_thread` in
        redis-py, but it is a coroutine. To launch it as a separate task, use
        ``asyncio.create_task``:

            >>> task = asyncio.create_task(pubsub.run())

        To shut it down, use asyncio cancellation:

            >>> task.cancel()
            >>> await task
        """
        ...
    


class PubsubWorkerExceptionHandler(Protocol):
    def __call__(self, e: BaseException, pubsub: PubSub): # -> None:
        ...
    


class AsyncPubsubWorkerExceptionHandler(Protocol):
    async def __call__(self, e: BaseException, pubsub: PubSub): # -> None:
        ...
    


PSWorkerThreadExcHandlerT = Union[PubsubWorkerExceptionHandler, AsyncPubsubWorkerExceptionHandler]
CommandT = Tuple[Tuple[Union[str, bytes], ...], Mapping[str, Any]]
CommandStackT = List[CommandT]
class Pipeline(Redis):
    """
    Pipelines provide a way to transmit multiple commands to the Redis server
    in one transmission.  This is convenient for batch processing, such as
    saving all the values in a list to Redis.

    All commands executed within a pipeline(when running in transactional mode,
    which is the default behavior) are wrapped with MULTI and EXEC
    calls. This guarantees all commands executed in the pipeline will be
    executed atomically.

    Any command raising an exception does *not* halt the execution of
    subsequent commands in the pipeline. Instead, the exception is caught
    and its instance is placed into the response list returned by execute().
    Code iterating over the response list should be able to deal with an
    instance of an exception as a potential value. In general, these will be
    ResponseError exceptions, such as those raised when issuing a command
    on a key of a different datatype.
    """
    UNWATCH_COMMANDS = ...
    def __init__(self, connection_pool: ConnectionPool, response_callbacks: MutableMapping[Union[str, bytes], ResponseCallbackT], transaction: bool, shard_hint: Optional[str]) -> None:
        ...
    
    async def __aenter__(self: _RedisT) -> _RedisT:
        ...
    
    async def __aexit__(self, exc_type, exc_value, traceback): # -> None:
        ...
    
    def __await__(self): # -> Generator[Any, None, Self]:
        ...
    
    _DEL_MESSAGE = ...
    def __len__(self): # -> int:
        ...
    
    def __bool__(self): # -> Literal[True]:
        """Pipeline instances should always evaluate to True"""
        ...
    
    async def reset(self): # -> None:
        ...
    
    async def aclose(self) -> None:
        """Alias for reset(), a standard method name for cleanup"""
        ...
    
    def multi(self): # -> None:
        """
        Start a transactional block of the pipeline after WATCH commands
        are issued. End the transactional block with `execute`.
        """
        ...
    
    def execute_command(self, *args, **kwargs) -> Union[Pipeline, Awaitable[Pipeline]]:
        ...
    
    async def immediate_execute_command(self, *args, **options): # -> None:
        """
        Execute a command immediately, but don't auto-retry on the supported
        errors for retry if we're already WATCHing a variable.
        Used when issuing WATCH or subsequent commands retrieving their values but before
        MULTI is called.
        """
        ...
    
    def pipeline_execute_command(self, *args, **options): # -> Self:
        """
        Stage a command to be executed when execute() is next called

        Returns the current Pipeline object back so commands can be
        chained together, such as:

        pipe = pipe.set('foo', 'bar').incr('baz').decr('bang')

        At some other point, you can then run: pipe.execute(),
        which will execute all commands queued in the pipe.
        """
        ...
    
    def raise_first_error(self, commands: CommandStackT, response: Iterable[Any]): # -> None:
        ...
    
    def annotate_exception(self, exception: Exception, number: int, command: Iterable[object]) -> None:
        ...
    
    async def parse_response(self, connection: Connection, command_name: Union[str, bytes], **options): # -> None:
        ...
    
    async def load_scripts(self): # -> None:
        ...
    
    async def execute(self, raise_on_error: bool = ...) -> List[Any]:
        """Execute all the commands in the current pipeline"""
        ...
    
    async def discard(self): # -> None:
        """Flushes all previously queued commands
        See: https://redis.io/commands/DISCARD
        """
        ...
    
    async def watch(self, *names: KeyT): # -> Pipeline:
        """Watches the values at keys ``names``"""
        ...
    
    async def unwatch(self): # -> Pipeline | Literal[True]:
        """Unwatches all previously specified keys"""
        ...
    


