"""
This type stub file was generated by pyright.
"""

from typing import TYPE_CHECKING
from redis.asyncio.client import Pipeline, Redis

if TYPE_CHECKING:
    ...
def from_url(url, **kwargs): # -> Redis:
    """
    Returns an active Redis client generated from the given database URL.

    Will attempt to extract the database id from the path url fragment, if
    none is provided.
    """
    ...

class pipeline:
    def __init__(self, redis_obj: Redis) -> None:
        ...
    
    async def __aenter__(self) -> Pipeline:
        ...
    
    async def __aexit__(self, exc_type, exc_value, traceback): # -> None:
        ...
    


