"""
This type stub file was generated by pyright.
"""

class Encoder:
    "Encode strings to bytes-like and decode bytes-like to strings"
    __slots__ = ...
    def __init__(self, encoding, encoding_errors, decode_responses) -> None:
        ...
    
    def encode(self, value): # -> bytes | memoryview[Any]:
        "Return a bytestring or bytes-like representation of the value"
        ...
    
    def decode(self, value, force=...): # -> str:
        "Return a unicode string from the bytes-like representation"
        ...
    


