"""
This type stub file was generated by pyright.
"""

from .base import AsyncPushNotificationsParser, PushNotificationsParser, _AsyncRESPBase, _RESPBase

class _RESP3Parser(_RESPBase, PushNotificationsParser):
    """RESP3 protocol implementation"""
    def __init__(self, socket_read_size) -> None:
        ...
    
    def handle_pubsub_push_response(self, response):
        ...
    
    def read_response(self, disable_decoding=..., push_request=...): # -> ResponseError | int | float | bool | list[Any] | bytes | dict[Any, Any] | None:
        ...
    


class _AsyncRESP3Parser(_AsyncRESPBase, AsyncPushNotificationsParser):
    def __init__(self, socket_read_size) -> None:
        ...
    
    async def handle_pubsub_push_response(self, response):
        ...
    
    async def read_response(self, disable_decoding: bool = ..., push_request: bool = ...): # -> EncodableT | ResponseError | None:
        ...
    


