"""
This type stub file was generated by pyright.
"""

from .base import _AsyncRESPBase, _RESPBase

class _RESP2Parser(_RESPBase):
    """RESP2 protocol implementation"""
    def read_response(self, disable_decoding=...): # -> ResponseError | int | bytes | list[Any] | None:
        ...
    


class _AsyncRESP2Parser(_AsyncRESPBase):
    """Async class for the RESP2 protocol"""
    async def read_response(self, disable_decoding: bool = ...): # -> EncodableT | ResponseError | None:
        ...
    


