"""
This type stub file was generated by pyright.
"""

import json
from redis._parsers.helpers import pairs_to_dict
from redis.commands.vectorset.utils import parse_vemb_result, parse_vlinks_result, parse_vsim_result
from ..helpers import get_protocol_version
from .commands import VEMB_CMD, VGETATTR_CMD, VINFO_CMD, VLINKS_CMD, VSIM_CMD, VectorSetCommands

class VectorSet(VectorSetCommands):
    def __init__(self, client, **kwargs) -> None:
        """Create a new VectorSet client."""
        ...
    


