"""
This type stub file was generated by pyright.
"""

from enum import Enum
from typing import Awaitable, Dict, List, Optional, Union
from redis.typing import CommandsProtocol, EncodableT, KeyT, Number

VADD_CMD = ...
VSIM_CMD = ...
VREM_CMD = ...
VDIM_CMD = ...
VCARD_CMD = ...
VEMB_CMD = ...
VLINKS_CMD = ...
VINFO_CMD = ...
VSETATTR_CMD = ...
VGETATTR_CMD = ...
VRANDMEMBER_CMD = ...
class QuantizationOptions(Enum):
    """Quantization options for the VADD command."""
    NOQUANT = ...
    BIN = ...
    Q8 = ...


class CallbacksOptions(Enum):
    """Options that can be set for the commands callbacks"""
    RAW = ...
    WITHSCORES = ...
    ALLOW_DECODING = ...
    RESP3 = ...


class VectorSetCommands(CommandsProtocol):
    """Redis VectorSet commands"""
    def vadd(self, key: KeyT, vector: Union[List[float], bytes], element: str, reduce_dim: Optional[int] = ..., cas: Optional[bool] = ..., quantization: Optional[QuantizationOptions] = ..., ef: Optional[Number] = ..., attributes: Optional[Union[dict, str]] = ..., numlinks: Optional[int] = ...) -> Union[Awaitable[int], int]:
        """
        Add vector ``vector`` for element ``element`` to a vector set ``key``.

        ``reduce_dim`` sets the dimensions to reduce the vector to.
                If not provided, the vector is not reduced.

        ``cas`` is a boolean flag that indicates whether to use CAS (check-and-set style)
                when adding the vector. If not provided, CAS is not used.

        ``quantization`` sets the quantization type to use.
                If not provided, int8 quantization is used.
                The options are:
                - NOQUANT: No quantization
                - BIN: Binary quantization
                - Q8: Signed 8-bit quantization

        ``ef`` sets the exploration factor to use.
                If not provided, the default exploration factor is used.

        ``attributes`` is a dictionary or json string that contains the attributes to set for the vector.
                If not provided, no attributes are set.

        ``numlinks`` sets the number of links to create for the vector.
                If not provided, the default number of links is used.

        For more information see https://redis.io/commands/vadd
        """
        ...
    
    def vsim(self, key: KeyT, input: Union[List[float], bytes, str], with_scores: Optional[bool] = ..., count: Optional[int] = ..., ef: Optional[Number] = ..., filter: Optional[str] = ..., filter_ef: Optional[str] = ..., truth: Optional[bool] = ..., no_thread: Optional[bool] = ..., epsilon: Optional[Number] = ...) -> Union[Awaitable[Optional[List[Union[List[EncodableT], Dict[EncodableT, Number]]]]], Optional[List[Union[List[EncodableT], Dict[EncodableT, Number]]]],]:
        """
        Compare a vector or element ``input``  with the other vectors in a vector set ``key``.

        ``with_scores`` sets if the results should be returned with the
                similarity scores of the elements in the result.

        ``count`` sets the number of results to return.

        ``ef`` sets the exploration factor.

        ``filter`` sets filter that should be applied for the search.

        ``filter_ef`` sets the max filtering effort.

        ``truth`` when enabled forces the command to perform linear scan.

        ``no_thread`` when enabled forces the command to execute the search
                on the data structure in the main thread.

        ``epsilon`` floating point between 0 and 1, if specified will return
                only elements with distance no further than the specified one.

        For more information see https://redis.io/commands/vsim
        """
        ...
    
    def vdim(self, key: KeyT) -> Union[Awaitable[int], int]:
        """
        Get the dimension of a vector set.

        In the case of vectors that were populated using the `REDUCE`
        option, for random projection, the vector set will report the size of
        the projected (reduced) dimension.

        Raises `redis.exceptions.ResponseError` if the vector set doesn't exist.

        For more information see https://redis.io/commands/vdim
        """
        ...
    
    def vcard(self, key: KeyT) -> Union[Awaitable[int], int]:
        """
        Get the cardinality(the number of elements) of a vector set with key ``key``.

        Raises `redis.exceptions.ResponseError` if the vector set doesn't exist.

        For more information see https://redis.io/commands/vcard
        """
        ...
    
    def vrem(self, key: KeyT, element: str) -> Union[Awaitable[int], int]:
        """
        Remove an element from a vector set.

        For more information see https://redis.io/commands/vrem
        """
        ...
    
    def vemb(self, key: KeyT, element: str, raw: Optional[bool] = ...) -> Union[Awaitable[Optional[Union[List[EncodableT], Dict[str, EncodableT]]]], Optional[Union[List[EncodableT], Dict[str, EncodableT]]],]:
        """
        Get the approximated vector of an element ``element`` from vector set ``key``.

        ``raw`` is a boolean flag that indicates whether to return the
                interal representation used by the vector.


        For more information see https://redis.io/commands/vembed
        """
        ...
    
    def vlinks(self, key: KeyT, element: str, with_scores: Optional[bool] = ...) -> Union[Awaitable[Optional[List[Union[List[Union[str, bytes]], Dict[Union[str, bytes], Number]]]]], Optional[List[Union[List[Union[str, bytes]], Dict[Union[str, bytes], Number]]]],]:
        """
        Returns the neighbors for each level the element ``element`` exists in the vector set ``key``.

        The result is a list of lists, where each list contains the neighbors for one level.
        If the element does not exist, or if the vector set does not exist, None is returned.

        If the ``WITHSCORES`` option is provided, the result is a list of dicts,
        where each dict contains the neighbors for one level, with the scores as values.

        For more information see https://redis.io/commands/vlinks
        """
        ...
    
    def vinfo(self, key: KeyT) -> Union[Awaitable[dict], dict]:
        """
        Get information about a vector set.

        For more information see https://redis.io/commands/vinfo
        """
        ...
    
    def vsetattr(self, key: KeyT, element: str, attributes: Optional[Union[dict, str]] = ...) -> Union[Awaitable[int], int]:
        """
        Associate or remove JSON attributes ``attributes`` of element ``element``
        for vector set ``key``.

        For more information see https://redis.io/commands/vsetattr
        """
        ...
    
    def vgetattr(self, key: KeyT, element: str) -> Union[Optional[Awaitable[dict]], Optional[dict]]:
        """
        Retrieve the JSON attributes of an element ``elemet`` for vector set ``key``.

        If the element does not exist, or if the vector set does not exist, None is
        returned.

        For more information see https://redis.io/commands/vgetattr
        """
        ...
    
    def vrandmember(self, key: KeyT, count: Optional[int] = ...) -> Union[Awaitable[Optional[Union[List[str], str]]], Optional[Union[List[str], str]]]:
        """
        Returns random elements from a vector set ``key``.

        ``count`` is the number of elements to return.
                If ``count`` is not provided, a single element is returned as a single string.
                If ``count`` is positive(smaller than the number of elements
                            in the vector set), the command returns a list with up to ``count``
                            distinct elements from the vector set
                If ``count`` is negative, the command returns a list with ``count`` random elements,
                            potentially with duplicates.
                If ``count`` is greater than the number of elements in the vector set,
                            only the entire set is returned as a list.

        If the vector set does not exist, ``None`` is returned.

        For more information see https://redis.io/commands/vrandmember
        """
        ...
    


