"""
This type stub file was generated by pyright.
"""

class Document:
    """
    Represents a single document in a result set
    """
    def __init__(self, id, payload=..., **fields) -> None:
        ...
    
    def __repr__(self): # -> str:
        ...
    
    def __getitem__(self, item): # -> Any:
        ...
    


