"""
This type stub file was generated by pyright.
"""

from typing import Any

class ProfileInformation:
    """
    Wrapper around FT.PROFILE response
    """
    def __init__(self, info: Any) -> None:
        ...
    
    @property
    def info(self) -> Any:
        ...
    


