"""
This type stub file was generated by pyright.
"""

from typing import Optional

class Suggestion:
    """
    Represents a single suggestion being sent or returned from the
    autocomplete server
    """
    def __init__(self, string: str, score: float = ..., payload: Optional[str] = ...) -> None:
        ...
    
    def __repr__(self) -> str:
        ...
    


class SuggestionParser:
    """
    Internal class used to parse results from the `SUGGET` command.
    This needs to consume either 1, 2, or 3 values at a time from
    the return value depending on what objects were requested
    """
    def __init__(self, with_scores: bool, with_payloads: bool, ret) -> None:
        ...
    
    def __iter__(self): # -> Generator[Suggestion, Any, None]:
        ...
    


