"""
This type stub file was generated by pyright.
"""

from typing import Iterable

class RequestTokenErr(Exception):
    """
    Represents an exception during token request.
    """
    def __init__(self, *args) -> None:
        ...
    


class InvalidTokenSchemaErr(Exception):
    """
    Represents an exception related to invalid token schema.
    """
    def __init__(self, missing_fields: Iterable[str] = ...) -> None:
        ...
    


class TokenRenewalErr(Exception):
    """
    Represents an exception during token renewal process.
    """
    def __init__(self, *args) -> None:
        ...
    


