"""empty message

Revision ID: 2b0fddedc99b
Revises: 
Create Date: 2024-02-18 18:11:35.252359

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b0fddedc99b'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    _ = op.create_table('stage_completions',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('stage_id', sa.Integer(), nullable=False),
        sa.Column('game_id', sa.String(length=16), nullable=False),
        sa.Column('created_on', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('gametime', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
        sa.ForeignKeyConstraint(['stage_id'], ['stages.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stage_completions')
    # ### end Alembic commands ###
