"""
This type stub file was generated by pyright.
"""

class Path:
    """This class represents a path in a JSON value."""
    strPath = ...
    @staticmethod
    def root_path(): # -> Literal['.']:
        """Return the root path's string representation."""
        ...
    
    def __init__(self, path) -> None:
        """Make a new path based on the string representation in `path`."""
        ...
    
    def __repr__(self): # -> str | Any:
        ...
    


