"""
This type stub file was generated by pyright.
"""

import redis
from redis._parsers.helpers import bool_ok
from ..helpers import get_protocol_version, parse_to_list
from .commands import ALTER_CMD, CREATERULE_CMD, CREATE_CMD, DELETERULE_CMD, DEL_CMD, GET_CMD, INFO_CMD, MGET_CMD, MRANGE_CMD, MREVRANGE_CMD, QUERYINDEX_CMD, RANGE_CMD, REVRANGE_CMD, TimeSeriesCommands
from .info import TSInfo
from .utils import parse_get, parse_m_get, parse_m_range, parse_range

class TimeSeries(TimeSeriesCommands):
    """
    This class subclasses redis-py's `Redis` and implements RedisTimeSeries's
    commands (prefixed with "ts").
    The client allows to interact with RedisTimeSeries and use all of it's
    functionality.
    """
    def __init__(self, client=..., **kwargs) -> None:
        """Create a new RedisTimeSeries client."""
        ...
    
    def pipeline(self, transaction=..., shard_hint=...): # -> ClusterPipeline | Pipeline:
        """Creates a pipeline for the TimeSeries module, that can be used
        for executing only TimeSeries commands and core commands.

        Usage example:

        r = redis.Redis()
        pipe = r.ts().pipeline()
        for i in range(100):
            pipeline.add("with_pipeline", i, 1.1 * i)
        pipeline.execute()

        """
        ...
    


class ClusterPipeline(TimeSeriesCommands, redis.cluster.ClusterPipeline):
    """Cluster pipeline for the module."""
    ...


class Pipeline(TimeSeriesCommands, redis.client.Pipeline):
    """Pipeline for the module."""
    ...


