"""
This type stub file was generated by pyright.
"""

def list_to_dict(aList): # -> dict[str | Any | None, str | Any | None]:
    ...

def parse_range(response, **kwargs): # -> list[tuple[Any | float, ...]]:
    """Parse range response. Used by TS.RANGE and TS.REVRANGE."""
    ...

def parse_m_range(response): # -> list[Any]:
    """Parse multi range response. Used by TS.MRANGE and TS.MREVRANGE."""
    ...

def parse_get(response): # -> tuple[int, float] | None:
    """Parse get response. Used by TS.GET."""
    ...

def parse_m_get(response): # -> list[Any]:
    """Parse multi get response. Used by TS.MGET."""
    ...

